### ISSUE TITLE
oc client version on container is not the same as Origin deployment

### ISSUE THREAD

**Issue by jparrill** [ansibleplaybookbundle/apb-base#19]
Hi there,

Using the script **run_latest_build.sh**  to start a origin local cluster, the **oc** client version do not match with Origin version:

```
sh-4.2$ oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.30.0.1:443
openshift v3.9.0-alpha.4+a303fa3-389
kubernetes v1.9.1+a0ce1bc657
```

Then the APBs fails on execution because of the API changes.

**Dockerfile**: https://github.com/ansibleplaybookbundle/apb-base/blob/master/Dockerfile-nightly
**Rpms**: http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/

**Comment by jmontleon** [comment]
@jparrill Sorry for the long delay in response. run_latest_build.sh is maintained in openshift/ansible-service-broker. If this is still an issue (and I'm not missing something that would make it appropriate for this repo) can you open an issue against that repo so it can get proper attention?
